language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install coveralls
# command to run tests
script:
  coverage run --source=sbrew setup.py test
after_success:
  coveralls