sudo: true
language: python
python:
  - "2.7"
  - "3.5"
install:
  - pip install coveralls pep8 pep257 restructuredtext_lint
  - python setup.py install
script:
  - pep8 --ignore=E501 sbrew/*.py tests/*.py *.py
  - pep257 sbrew sbrewsh.py
  - rst-lint README.md
  - python setup.py test
after_success:
  - python setup.py coverage
  - coveralls
